# Generated by Django 5.2.7 on 2026-02-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='supplierledger',
            options={'ordering': ['-transaction_date', '-id'], 'verbose_name': 'Supplier Ledger', 'verbose_name_plural': 'Supplier Ledgers'},
        ),
    ]
