# Generated by Django 5.2.7 on 2025-12-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sqft_per_pcs',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
