# Generated by Django 5.2.7 on 2025-12-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_change_sqft_per_pcs_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_charge_per_unit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
