# Generated by Django 5.2.7 on 2026-02-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercommitment',
            options={'ordering': ['-commitment_date', '-id'], 'verbose_name': 'Customer Commitment', 'verbose_name_plural': 'Customer Commitments'},
        ),
    ]
