# Generated by Django 5.2.7 on 2025-12-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total delivery charges (auto-calculated, can be manually adjusted)', max_digits=15),
        ),
    ]
