# Generated by Django 5.2.7 on 2025-12-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_delivery_charges_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Customer deposit/advance payment for this order', max_digits=15),
        ),
    ]
