# Generated by Django 5.2.7 on 2025-12-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_customer_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='product_note',
            field=models.CharField(blank=True, help_text='Short note for this product item', max_length=255),
        ),
    ]
