# Generated by Django 5.2.7 on 2025-12-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorderitem_product_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount to be deducted from total', max_digits=15),
        ),
    ]
